function set_lang(obj){obj.disabled=1;u=obj.options[obj.selectedIndex].value;if(u){window.location.href=u;};return false;}
function isMobile(){var isMobile={Android:function(){return navigator.userAgent.match(/Android/i);},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i);},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i);},Opera:function(){return navigator.userAgent.match(/Opera Mini/i);},Windows:function(){return navigator.userAgent.match(/IEMobile/i);}};if(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows())return 1;}
function new_window(href,params){var h=screen.height;var w=screen.width;var w2=w/100*80;if(w2>1140){w2=1140;}
var h2=h/100*70;if(href.indexOf('randimg')>0){w2=620;h2=300;}
if(href.indexOf('print=true')<0&&href.indexOf('ftp')<0&&href.indexOf('support.')>0){if(href.indexOf('?')<0){href=href+'?';}
href=href+'&print=true';}
var newBlankWindow=window.open(href,'_blank','location=1,resizable=1,scrollbars=1,status=1,width='+w2+',height='+h2+',left='+(w-w2)/2+',top='+((h-h2)/2-20)+params);newBlankWindow.focus();}
function select_ch_name($obj){var $this=$($obj);if(!$this.is(":visible")){return}
var $span=$this.closest('span');if($span.hasClass('no_add_name')){return}
var $b=$span.find('b');if(!$b.length){$span.prepend('<b></b>');$b=$span.find('b');}
$b.text($this.find('option:selected').text());if(!$this.attr('disabled')&&$span.hasClass('dis'))$span.removeClass('dis');if($this.attr('disabled'))$span.addClass('dis');}
$(document).ready(function(){$('#content_ajax a[new_window=1]').live('click',function(){var href=this.href;new_window(href);return false;});$('header, section, article, aside, footer, .cb').append('<b class="fc"></b>');$('.arr-left').prepend('<b>&nbsp;</b>');$('.arr-delete').prepend('<b>&nbsp;</b>');$('.p5-list .p5-vis').live('click',function(){$(this).parents('.border-on').find('.p5-keys').toggleClass('hidden');return false;});$('.p5-list111 textarea').focusin(function(){$(this).toggleClass('border');$(this).parent().next().children().toggleClass('off');return false;});$('.p5-list1111 textarea').focusout(function(){$(this).toggleClass('border');$(this).parent().next().children().toggleClass('off');return false;});$('.p6-note .btns a').click(function(){var node=$('#'+$(this).attr('for'));node.val($(this).attr('val'));$(this).parent().find('.bg-purple').removeClass('bg-purple').addClass('bg-gray');$(this).removeClass('bg-gray').addClass('bg-purple');return false;});var $lang_sel=$("select[name=lang_switch]");$lang_sel.val($lang_sel.find('option[selected]').val());$lang_sel.change(function(){return set_lang(this);});$('.frm select').each(function(){select_ch_name(this);});$('.frm select').change(function(){select_ch_name(this);});$('.frm label').live('click',function(){var node=$('#'+$(this).attr('for'));if(!$(this).hasClass("checked")){node.get(0).checked=true;$(this).addClass("checked");}
else{node.removeAttr("checked");$(this).removeClass("checked");}
node.trigger('change');if($('#file_block').length){node.trigger('click',[1]);}
return false;});$('.frm input[type="text"]').focusin(function(){$(this).addClass('focus');if($(this).val()==$(this).attr('def'))$(this).val('');});$('.frm input[type="text"]').focusout(function(){if($(this).val()=='')$(this).val($(this).attr('def')).removeClass('focus');});$('.psw').focus(function(){$(this).addClass('off');$(this).next().removeClass('off').trigger('focus');});$('.frm input[type="password"]').focusout(function(){if($(this).val()=='')$(this).addClass('off').prev().removeClass('off');else $(this).prev().val($(this).prev().attr('name'));});$('.frm input[type="file"]').each(function(){$(this).css('width',$(this).parent().width());$(this).css('height',$(this).parent().height());});$('.frm input[type="file"]').change(function(){$('#file-inp-serv').css('display','block');});$('a[type="submit"]').live("click",function(){if($(this).attr('disabled')){return false;}
$(this).attr('disabled','on');$(this).parents('form').submit();return false;});$('a[type="reset"]').live("click",function(){$(this).closest('form').get(0).reset();return false;});function slideOut(obj,speed,fn){if(obj.length&&!obj.is(':hidden')){obj.animate({opacity:0,height:'0'},speed,'swing',function(){$(this).css({visibility:'hidden'}).hide();fn();});}else{fn();}}
$('#error_clear').live('click',function(event){event.preventDefault();slideOut($('#error_block'),'300',function(){});return false;});$(window).load(function(){$('select.lang_switch').change(function(){ga('send','event','Header','Select','Change Language');});$('a.ga_title').click(function(){ga('send','event','Header','Click','Home');});$('a.ga_My_Requests').click(function(){ga('send','event','Header','Click','My Requests');});$('a.ga_Activations').click(function(){ga('send','event','Header','Click','My Codes');});$('a.ga_Store').click(function(){ga('send','event','Header','Click','KPC Store');});$('a.ga_Devices').click(function(){ga('send','event','Header','Click','KPC Devices');});$('a.ga_Profile').click(function(){ga('send','event','Header','Click','Profile');});$('a.ga_New_Request').click(function(){ga('send','event','Header','Click','New Request');});$('a.ga_Requests').click(function(){ga('send','event','Header','Click','Requests');});$('a.ga_Log_out').click(function(){$('p.user_info').css('opacity',0.3);ga('send','event','Header','Click','Log out');});$('a.ga_Footer_Marketing').click(function(){ga('send','event','Footer','Click','Marketing');});$('a.ga_Footer_KPC').click(function(){ga('send','event','Footer','Click','KPC');});$('a.ga_Footer_FORUM').click(function(){ga('send','event','Footer','Click','Forum');});$('a.ga_Footer_KnowledgeBase').click(function(){ga('send','event','Footer','Click','KnowledgeBase');});$('a.ga_Footer_Privacy').click(function(){ga('send','event','Footer','Click','Privacy Statement');});$('a.ga_Footer_FAQ').click(function(){ga('send','event','Footer','Click','FAQ');});$('a.ga_Footer_Contacts').click(function(){ga('send','event','Footer','Click','Contacts');});});});